### ISSUE TITLE
Rename repo.

### ISSUE THREAD

**Issue by brb3** [devanooga/devanooga.com#33]
@seabre added a fix in #23 to prevent Github from trying to process the repo as a Github Pages site.

I'd also like to move the repo from `devanooga.github.io` to just `devanooga` or `website` or something like that.

This isn't something we really _need_, so I'm going to kind of back burner this.

**Comment by agarzola** [comment]
Reminder for when this _does_ get done: the site makes reference to this repo in the CoC. That’s link’s URL will need to get changed. My vote is for either `website` or `devanooga.com`; simply `devanooga` is too vague, in my opinion.

All of that said, I’d suggest doing it sooner, rather than later, before folks from the community decide they want to contribute somehow and then we go and break their remotes. Not that that’s a big deal, but it does seem unnecessary.
