### ISSUE TITLE
Community volunteers section?

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga.com#44]
Maybe something we can tuck away on the front page or something (I dunno I suck at design)? Somewhere where we can put up positions we're currently looking to fill. Mainly came out of the job board discussion. While I don't mind pitching in, it's nice to be able to spread responsibility of our functions out to people that are interested in working those sections.

**Comment by agarzola** [comment]
This sounds like exactly the use case for the `roles` property on the member files.

It would also be nice to add a _Volunteer_ badge to these individuals on the members page. Something small and strictly CSS-based that acknowledges their efforts.

**Comment by 7279616e** [comment]
> Something small and strictly CSS-based that acknowledges their efforts.

For example, css 'badge' that overlays their member imagine in the bottom (or bottom corner)? Happy to implement it in spare time, if you guys can decide on how you want it to look. 

```
organizer: true
volunteer: true
```

**Comment by agarzola** [comment]
Exactly! A sweet little CSS badge. Feel free to take the lead on that, @7279616e! As much as possible, try to design them so they’re easily expandable (i.e. it’s easy to design new badges that look consistent with the rest, without much hassle).

Thanks!

**Comment by brb3** [comment]
Would we want one for "backer" or something like that, to mark people that have donated financially?

**Comment by agarzola** [comment]
I’d say yes.

**Comment by 7279616e** [comment]
> easily expandable
salient parameter

Thinking aloud (please correct/opine otherwise):

- Employ same font as elsewhere on devanooga site - [Asap](https://fonts.google.com/specimen/Asap)

- Make the label succinct
- Keep it simple
- Uniform text color and weight on all badges (i.e. backer, volunteer)
- Perhaps vary background color of badge with muted colors similar to the current accent color - [#E0644F](http://www.colorhexa.com/e0644f)
- Perhaps something as simple as a thin rectangle overlay at the bottom of the member image?

**Comment by brb3** [comment]
No complaints from me on any of this. Is this something you want to take a stab at implementing @7279616e ?

**Comment by 7279616e** [comment]
In typing that out, it was an attempt to shorten the gap between between parameters specified and the end result in which all agree on. 

My initial idea was to take it from "here is the final design/mockup of the badge in which leadership has approved" to  `volunteer: true` working as desired. Anyone have any back-of-the-napkin doodles from which to start? I have no opinion on how it should look. Only aiming to support those that do.

**Comment by 7279616e** [comment]
Question: 

Preferences on A, B, C, D, or <create-your-own>? 

http://i.imgur.com/FnCbw9n.jpg

**Comment by brb3** [comment]
I would go with `A`

**Comment by 7279616e** [comment]
That makes it simple. I'll proceed.

**Comment by StrangeWill** [comment]
I too like A or D (assuming D also has text in it like A), only hangup I have is what if someone is in more than one role, will it just continue stacking them (assuming we're going to be more detailed in what they're doing)?

**Comment by 7279616e** [comment]
> what if someone is in more than one role

Very good point. One in which I had not considered. 

Also, with D, the idea was to match the slant to the slant on the devanooga title on the page. 

Someone want to sketch an idea of how an image with 2 roles would appear?

**Comment by StrangeWill** [comment]
> Also, with D, the idea was to match the slant to the slant on the devanooga title on the page.

Yeah that's what I thought the intent was.

I got something I need to get done right now and I'll see about sketching something. I mean honestly is someone going to be in more than a handful of roles? Not really sure...

**Comment by 7279616e** [comment]
No need to rush or worry about timing, sir. Just adding that I'm happy to implement, once the design idea is fairly easy to visualize. Hard for an engineer to design for things that are subjective to preferences.

**Comment by agarzola** [comment]
Something like B with the first letter of the role inside it would look cleaner. Keep in mind you won’t be looking at one picture with a role beneath it; you’ll be looking at a grid with dozens of pictures. They won’t all have roles, but my point is there’s no need to repeat the words over and over.

We assign a color to each role. In order to keep things meaningful, we should include the whole word in the markup (_volunteer_, _organizer_) and wrap everything but the first letter in an element that we hide from the screen (but keep accessible to scrapers, screen readers, text selection, maybe printers). At that point, we could probably do something fun, like expanding the badge to include the full word under certain circumstances. This last bit we’d have to consider very carefully, but I think it’s an opportunity for something both useful and cool.

Here are some colors I had come up with during the sketching phase of the site’s design. I think they work very well for these badges:
- `#5F9ADE` : blue
- `#96BA71` : green
- `#A97FCE` : lilac
- `#F7BC5B` : yellow
- `#707070` : gray

**Comment by 7279616e** [comment]
Excellent points and a great set of colors.

**Comment by 7279616e** [comment]
> At that point, we could probably do something fun, like expanding the badge to include the full word under certain circumstances. This last bit we’d have to consider very carefully, but I think it’s an opportunity for something both useful and cool.

Erring on the side of over-communication, will this be in v1? I ask, because I'm probably the least imaginative in the group, and would have to surrender the concept development to a grown up. lol

**Comment by StrangeWill** [comment]
I don't mind relying on something silly like tooltips for v1, I don't want to be hung up on someone struggling with design on something we can iterate with.

**Comment by agarzola** [comment]
Agreed.

**Comment by StrangeWill** [comment]
Closing this as #75 addresses this.
