### ISSUE TITLE
Beginner Developer Guide

### ISSUE THREAD

**Issue by 7279616e** [devanooga/devanooga.com#65]
Would it be beneficial to have some sort of content/guide in which there are either affiliate links with devanooga as the recipient or referral links (like DO's) for resources to be used on hack night and the like? 

Reasons behind this idea

- Local Developer NPO seen as source of authority
- Some sort of very basic privacy guide as an example? i.e. PIA
- Content would be a value add to the org (similar to the blog idea)

Cons:

- Making content is hard work
- Making great content people actually read is even harder
- The time invested in this relative to payout is likely not a great ratio
- I've done affiliate stuff previously, and it takes a long time between creation -> traction -> conversion -> and the often quarterly payouts. 

Suggestion:

If there is any merit to some derivative of this idea, perhaps sticking to some sort of referral program in which resources are bestowed to devanooga would be a cleaner/better starting point.

**Comment by StrangeWill** [comment]
I think one point of pain: our main group right now is the _entrenched_ developers, we're not getting many "new" devs on board right now (we've discussed some stuff to start the ball rolling on this, I really do need to reach out to language-specific circles in town to get them to join too).

Secondly as you said, I'm unsure about the amount of traction we get, even if we're "top dog" IT resources in town, we still only have reaches counting in the _hundreds_, will that bring in enough affiliate revenue to be worth it? Hmm... it's worth investigating.

Also I'm somewhat weary about content that drives money like that, as long as we're clear we promote affiliate links because they're products we support first, and we're affiliates because we _believe in the product that much_ (a-la Penny Arcade's marketing model back in the day), I'm fine. As long as we don't start promoting trash because we may make money off of it.


I guess the first question is what kind of affiliate programs could we lean on, and what does that revenue look like?

**Comment by 7279616e** [comment]
> Not many new devs

> Even with traction, still referring to _hundreds_

With those points in mind, I think you're right. The $$ kind would not likely be worth the effort. 

> weary about content that drives money like that

Also a solid point. This was the reason so many terrible shared hosts were popular in the early 00s. Affiliate commission for 50% of all signups biased the mindshare negatively. 

What about something simple like the referral programs where credit is given to Devanooga? I'm not sure what providers offer such a thing, but even when a veteran dev signs up for a service for the first time, why not use the Dev referral link? 

[Digital Ocean](https://www.digitalocean.com/referral-program/) is the one that came to mind. 

Disclosure: 
The entire idea came from the internet privacy laws in the news this week. I wrote a little html email about VPNs (and PIA) for a list of contacts I have under the <needlessly bothers me with IT questions they should direct to their MSP> label in my contacts. Less than 20 conversions thus far, but it was just an attempt to monetize the nagging.

**Comment by brb3** [comment]
I'm late to the party since this issue has been closed, but just wanted to throw in my 2 cents.

I do like the idea of a "beginner's guide". Maybe we link to things like Digital Ocean (or services that we like) and also have a "If you want to help support devanooga, use our referral link" and link to that as well.

Just spit-balling.
